version: '3.9'

services:
  service_1:
    build:
      context: ./service_1
    container_name: service_1
    ports:
      - "8081:8080"  # Local debugging (optional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3

  service_2:
    build:
      context: ./service_2
    container_name: service_2
    ports:
      - "8001:8000"  # Local debugging (optional)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
